# Generated by Django 5.1.4 on 2024-12-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoNobel', '0002_rename_coordinates_sportstructure_address_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='rating_range',
        ),
    ]
